# Generated by Django 5.2.6 on 2025-09-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="tariff",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
